### 회원가입
POST localhost:19045/api/auth/sign-up
Content-Type: application/json

{
  "username": "user12",
  "password": "#sparta12",
  "nickname": "유저12",
  "email": "user12@email.com",
  "slack_id": "U12RFDJRQEB"
}

### 로그인
POST localhost:19045/api/auth/sign-in
Content-Type: application/json

{
  "username": "user12",
  "password": "#sparta12"
}

### 토큰 재발급
POST localhost:19045/api/auth/token
Content-Type: application/json
X-Refresh-Token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjo2NTQ5NTk5MjIyMDYxMjY4MzIsInVzZXJfcm9sZSI6IkNVU1RPTUVSIiwiaXNzIjoiYXV0aCIsImlhdCI6MTczNDAwNTQ5NiwiZXhwIjoxNzM0MDE2Mjk2fQ._2IZbTlEHjtZ8Cm2CPqDdiKH4g5rgdAUsQhA8-uHfKCGVVLPSdBBnTwsVPm73K4-l6-uLT0_RyZXUcy6CrMbAA

