### 회원가입
POST localhost:19045/api/auth/sign-up
Content-Type: application/json

{
  "username": "master",
  "password": "#sparta12",
  "nickname": "마스터",
  "email": "master@email.com",
  "slack_id": "M12RFDJRQEB"
}

### 로그인
POST localhost:19045/api/auth/sign-in
Content-Type: application/json

{
  "username": "master",
  "password": "#sparta12"
}

### 토큰 재발급
POST localhost:19045/api/auth/token
Content-Type: application/json
X-Refresh-Token: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjo2NTQ5NTk5MjIyMDYxMjY4MzIsInVzZXJfcm9sZSI6IkNVU1RPTUVSIiwiaXNzIjoiYXV0aCIsImlhdCI6MTczNDAyMDg3NSwiZXhwIjoxNzM0MDMxNjc1fQ.fObp0tyF3ayWFoPPilou5_uObKRerAsnyoxvXZDSwNvZYspeCO4HQsnZGexQwjrBnKOrp0Qcxxwpogw-WtGrmA

### 사용자 정보 조회 (자신)
GET localhost:19045/api/users/654959922206126832
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjo2NTQ5NTk5MjIyMDYxMjY4MzIsInVzZXJfcm9sZSI6IkNVU1RPTUVSIiwiaXNzIjoiYXV0aCIsImlhdCI6MTczNDAyMTAxMywiZXhwIjoxNzM0MDIxNjEzfQ.czHcWtuf8gXj2IE0otT724dvMtIb49pONZnK7HlistXHykjlC7F6GTOCahwayMVPnNhYpKbG16xhD-6w3pzqFQ
X-User-Id: 654959922206126832

### 사용자 정보 변경
PUT localhost:19045/api/users/654959922206126832
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjo2NTQ5NTk5MjIyMDYxMjY4MzIsInVzZXJfcm9sZSI6IkNVU1RPTUVSIiwiaXNzIjoiYXV0aCIsImlhdCI6MTczNDA1ODMyMiwiZXhwIjoxNzM0MDU4OTIyfQ.kzrnCOAOt-CAH3KdnLoVABA4qCOfeA4GZ3TOMv4pfKj58kh6W3IM1N9iVKQ_tsov0QSBlzf9TOlgKBKfXFxrqQ
X-User-Id: 654959922206126832
X-User-Role: MASTER

{
  "nickname": "매니저13",
  "email": "user13@email.com",
  "slack_id": "U13RFDJRQEB"
}

### 사용자 권한 변경
PATCH localhost:19045/api/users/655384684086497877
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjo2NTUzODQ2ODQwODY0OTc4NzcsInVzZXJfcm9sZSI6IkNVU1RPTUVSIiwiaXNzIjoiYXV0aCIsImlhdCI6MTczNDA5MjY5NywiZXhwIjoxNzM0MDkzMjk3fQ.djc3MN-wh8O8CYrnzdZuRvFbmn7SXNo3-Ytwwkn-MdBGKyQJJB63foytXM_1fqV5cVNvUr3GWAZxocAxZy3p6w
X-User-Id: 655384684086497877
X-User-Role: MASTER

{
  "role": "HUB_MANAGER"
}