server:
  port: 19090

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    import: classpath:application-key.yml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        user_sql_comments: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19040/eureka